version: 2.1
jobs:
  cloudformation-stack:
    machine: # executor type
      image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      - checkout
      - run:
          name: "Upload files"
          command: |
            cd infrastructura
            aws s3 cp cloudformation s3://demo-cloudformation-template-elmer --recursive
      - run:
          name: "Deploy cloudformation stack"
          command: |
            cd infrastructura/cloudformation
            #aws cloudformation deploy --template-file ./principal.yml --stack-name demo --parameter-overrides BDPASS=$BD_PASS BDUSER=$BD_USER BucketS3="https://demo-cloudformation-template-elmer.s3-us-west-2.amazonaws.com"
  CI:
    machine: # executor type
      image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      - checkout
      - run:
          name: "Login docker hub"
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run:
          name: "Build image"
          command: |
            echo "hello"
workflows:
  version: 2
  build_and_test:
    jobs:
      - cloudformation-stack:
          filters:
            branches:
              only: infrastructura
      - CI:
          filters:
            branches:
              only: developer
