version: 2.1
jobs:
  prebuild:
    working_directory: ~/infrastructura/cloudformation
    machine: # executor type
      image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      - checkout
      - run:
          name: "Wait until service reach steady state"
          command: |
            aws s3 ls
workflows:
  version: 2
  build_and_test:
    jobs:
      - prebuild
