version: 2.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run: echo "Run your code here"
orbs:
  aws-cli: circleci/aws-cli@1.3.2
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
