version: 2.1
jobs:
  prebuild:
    working_directory: ~/infrastructura/cloudformation
    machine: # executor type
      image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      - checkout
      - run:
          name: "Deploy cloudformation stack"
          command: |
            aws cloudformation deploy --template-file ./principal.yml --stack-name demo --parameter-overrides BDPASS=$BD_PASS BDUSER=$BD_USER BucketS3="https://demo-cloudformation-template-elmer.s3-us-west-2.amazonaws.com"
workflows:
  version: 2
  build_and_test:
    jobs:
      - prebuild
