Description: Template para instancias.

Parameters:
  RefSubnetPublica:
    Description: "Subnet Publica"
    Type: String

  RefSG:
    Description: "Security group"
    Type: String

  RefDefaultSG:
    Description: "Default Security group"
    Type: String

  EC2TYPE:
    Description: "Tipo EC2TYPE"
    Type: String
    Default: t2.micro

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0e8c04af2729ff1bb"
      KeyName: "EC2Tutorial"
      InstanceType: !Ref EC2TYPE
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref RefSubnetPublica
          GroupSet:
            - !Ref RefSG
            - !Ref RefDefaultSG
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - - "InstanceBastion"
              - !Ref AWS::StackName
        - Key: Owner
          Value: elmerreal98@gmail.com
